// vecadd — first C testcase: c[i] = a[i] + b[i], N=16, single hart.
// Inputs are deterministic (a[i]=3i+1, b[i]=7i+2 -> c[i]=10i+3) so the
// UVM scoreboard can independently check the output region at OUT_ADDR
// (see vecadd.expected.hex, generated by dv/sw/Makefile).
// Self-check too: returns 0 on match (crt0 -> PASS magic).

#define N        16
#define OUT_ADDR 0x80020000u

int main(void) {
  volatile unsigned *out = (volatile unsigned *)OUT_ADDR;
  unsigned a[N], b[N];

  for (int i = 0; i < N; i++) {
    a[i] = 3u * i + 1u;
    b[i] = 7u * i + 2u;
  }
  for (int i = 0; i < N; i++)
    out[i] = a[i] + b[i];

  for (int i = 0; i < N; i++)
    if (out[i] != 10u * i + 3u)
      return i + 1;
  return 0;
}
